### ISSUE TITLE
Rkyv: Failed compilation on s390x and armv7hl

### ISSUE THREAD

**Issue by remilauzier** [rkyv/rkyv#231]
error[E0412]: cannot find type `AtomicI16_be` in this scope
  --> src/impls/rend.rs:91:19
   |
91 | impl_rend_atomic!(AtomicI16_be, i16_be);
   |                   ^^^^^^^^^^^^ not found in this scope

Rkyv is not compilable on version 0.7.26 on these architecture. Was working in 0.7.24

https://kojipkgs.fedoraproject.org//work/tasks/2272/79802272/build.log
https://kojipkgs.fedoraproject.org//work/tasks/2277/79802277/build.log

**Comment by djkoloski** [comment]
Thanks for the bug report. rkyv recently expanded atomics support to more platforms, which appears to be the source of this issue. It looks like the specific platform is `armv7h1`, is that correct?

**Comment by remilauzier** [comment]
Yes, with s390x also.

**Comment by djkoloski** [comment]
I was able to reproduce this issue. It looks like rkyv does specify its rend dependency strictly enough since atomics support was expanded to more platforms. This is fixed in the following commits:

- https://github.com/rkyv/rkyv/commit/7f8506ee0c5fee3f650710bfbcec357c388331a6
- https://github.com/rkyv/rend/commit/ceb0ab1243469bf99c290b4a318984fe10e03676

`rend` has been updated to v0.3.6 and rkyv will require it as of the next release (v0.7.27),
