### ISSUE TITLE
Cannot compile rkyv with latest nightly rust

### ISSUE THREAD

**Issue by heiseish** [rkyv/rkyv#650]
## Context
- Trying to compile with rkyv `0.8.14` on latest nightly gives
```bash
error[E0599]: no method named `dangling` found for reference `&std::alloc::Layout` in the current scope
 --> /home/xxxxx/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rkyv-0.8.14/src/polyfill.rs:8:16
  |
8 |         layout.dangling()
  |                ^^^^^^^^
  |
help: there is a method `dangling_ptr` with a similar name
  |
8 |         layout.dangling_ptr()
```

```bash
❯ rustc -Vv
rustc 1.95.0-nightly (9e79395f9 2026-02-10)
binary: rustc
commit-hash: 9e79395f92bff6a8f536430e42a4beae69f60ff8
commit-date: 2026-02-10
host: x86_64-unknown-linux-gnu
release: 1.95.0-nightly
LLVM version: 22.1.0
```

**Comment by djkoloski** [comment]
Upgrading to 0.8.15 should fix this error.

**Comment by heiseish** [comment]
Thanks for the quick response!
