### ISSUE TITLE
`copy` feature fails on recent nightly compiler versions

### ISSUE THREAD

**Issue by gbj** [rkyv/rkyv#488]
## Steps to Reproduce

Create an empty project with `Cargo.toml`:
```toml
[package]
name = "rkyv_check"
version = "0.1.0"
edition = "2021"

[dependencies]
rkyv = { version = "0.7", features = [
  "copy"
] }
```

Run `cargo +nightly-2024-03-31 check`. (I haven't bisected to find the exact date, but it was working on `2024-01-29` and I think began failing soon after that.)

## Error output

```
    Checking rkyv v0.7.44
error[E0277]: the trait bound `NonZero<i8>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:108:33
    |
108 | unsafe impl ArchiveCopySafe for NonZeroI8 {}
    |                                 ^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<i8>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<u8>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:109:33
    |
109 | unsafe impl ArchiveCopySafe for NonZeroU8 {}
    |                                 ^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<u8>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<i16>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:128:37
    |
128 |     unsafe impl ArchiveCopySafe for NonZeroI16 {}
    |                                     ^^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<i16>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<i32>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:129:37
    |
129 |     unsafe impl ArchiveCopySafe for NonZeroI32 {}
    |                                     ^^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<i32>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<i64>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:130:37
    |
130 |     unsafe impl ArchiveCopySafe for NonZeroI64 {}
    |                                     ^^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<i64>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<i128>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:131:37
    |
131 |     unsafe impl ArchiveCopySafe for NonZeroI128 {}
    |                                     ^^^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<i128>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<u16>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:132:37
    |
132 |     unsafe impl ArchiveCopySafe for NonZeroU16 {}
    |                                     ^^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<u16>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<u32>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:133:37
    |
133 |     unsafe impl ArchiveCopySafe for NonZeroU32 {}
    |                                     ^^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<u32>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<u64>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:134:37
    |
134 |     unsafe impl ArchiveCopySafe for NonZeroU64 {}
    |                                     ^^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<u64>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

error[E0277]: the trait bound `NonZero<u128>: ArchiveCopy` is not satisfied
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:135:37
    |
135 |     unsafe impl ArchiveCopySafe for NonZeroU128 {}
    |                                     ^^^^^^^^^^^ the trait `ArchiveCopy` is not implemented for `NonZero<u128>`
    |
note: required by a bound in `ArchiveCopySafe`
   --> /Users/gjohnston/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.44/src/copy.rs:99:35
    |
99  | pub unsafe trait ArchiveCopySafe: ArchiveCopy + Sized {}
    |                                   ^^^^^^^^^^^ required by this bound in `ArchiveCopySafe`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rkyv` (lib) due to 10 previous errors
```

**Comment by djkoloski** [comment]
Just as a heads-up, this feature was always nightly-only and has since been broken by compiler updates. Maybe some of these issues could be fixed, but I'm not planning to fix them until after 0.8 gets published.

**Comment by gbj** [comment]
Fair enough -- I will just remove it from the place it was being used. Feel free to close if it's a known issue.

**Comment by djkoloski** [comment]
Yep, known issue. This feature has been removed, so this won't get fixed.
